# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f90ffd60bcdfa0416dfd7f11aaeaf13e689ab9b7ac87c52ad778fdd1c06dc71663fb9e66b6d944afdbc1ae86ff746a48f0a80ade04d6a1e27e237dbdf9364e

test:
  secret_key_base: 1eb8ef46395c8bab04ae7a10e7395c7c01f2ad645d7c4f2ab03c0f2843ba9f586137aba4cb0d2176c7b299a588f7e2cfb7579a812e9bc83c8e74c9dcf41a3a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
